import {
	orderControllerWechatJsapi,
	rideControllerAccept,
	rideControllerArriveDestination,
	rideControllerArrivePickup,
	rideControllerAvailability,
	rideControllerBusyDriverContact,
	rideControllerCancel,
	rideControllerContact,
	rideControllerCreate,
	rideControllerCreateDriverVehicle,
	rideControllerDetail,
	rideControllerDriverOrders,
	rideControllerDriverProfile,
	rideControllerDriverStatus,
	rideControllerDriverVehicles,
	rideControllerFinalize,
	rideControllerList,
	rideControllerMarkMessagesRead,
	rideControllerMessageUnreadCount,
	rideControllerMessages,
	rideControllerPlaces,
	rideControllerReverseGeocode,
	rideControllerReject,
	rideControllerReportLocation,
	rideControllerRoutePreview,
	rideControllerSendMessage,
	rideControllerStart,
	rideControllerUpdateDriverVehicle,
	rideControllerDeleteDriverVehicle,
	vehicleControllerMyVehicles,
} from '@wash/api-client';
import type { RideMessageDto, RideMessageReadResultDto, RideMessageUnreadCountDto, VehicleResponseDto } from '@wash/api-client';

const value = async <T>(promise: Promise<unknown>) => (await promise as unknown) as T;

export const rideApi = {
	availability: (longitude: number, latitude: number) => value<any>(rideControllerAvailability({ longitude, latitude })),
	places: (keywords: string, city?: string, location?: { longitude: number; latitude: number }) => value<any[]>(rideControllerPlaces({ keywords, city, ...location })),
	reverseGeocode: (longitude: number, latitude: number) => value<any>(rideControllerReverseGeocode({ longitude, latitude })),
	preview: (payload: any) => value<any>(rideControllerRoutePreview(payload)),
	create: (payload: any) => value<any>(rideControllerCreate(payload)),
	list: (params: any = {}) => value<any>(rideControllerList(params)),
	detail: (id: number) => value<any>(rideControllerDetail(id)),
	cancel: (id: number, reason?: string) => value<any>(rideControllerCancel(id, { reason })),
	contact: (id: number) => value<any>(rideControllerContact(id)),
	busyDriverContact: (memberId: number) => value<any>(rideControllerBusyDriverContact(memberId)),
	messages: (id: number) => value<RideMessageDto[]>(rideControllerMessages(id)),
	messageUnreadCount: (id: number) => value<RideMessageUnreadCountDto>(rideControllerMessageUnreadCount(id)),
	markMessagesRead: (id: number) => value<RideMessageReadResultDto>(rideControllerMarkMessagesRead(id)),
	sendMessage: (id: number, content: string) => value<RideMessageDto>(rideControllerSendMessage(id, { content })),
	driverProfile: () => value<any>(rideControllerDriverProfile()),
	driverStatus: (status: 'OFFLINE' | 'AVAILABLE' | 'BUSY') => value<any>(rideControllerDriverStatus({ status } as any)),
	driverOrders: (params: any = {}) => value<any>(rideControllerDriverOrders(params)),
	driverVehicles: () => value<any[]>(rideControllerDriverVehicles()),
	memberVehicles: () => value<VehicleResponseDto[]>(vehicleControllerMyVehicles()),
	createDriverVehicle: (payload: any) => value<any>(rideControllerCreateDriverVehicle(payload)),
	updateDriverVehicle: (id: number, payload: any) => value<any>(rideControllerUpdateDriverVehicle(id, payload)),
	deleteDriverVehicle: (id: number) => value<any>(rideControllerDeleteDriverVehicle(id)),
	accept: (id: number) => value<any>(rideControllerAccept(id)),
	reject: (id: number) => value<any>(rideControllerReject(id)),
	arrivePickup: (id: number, confirmFarAway = false) => value<any>(rideControllerArrivePickup(id, { confirmFarAway })),
	start: (id: number, phoneLastFour: string) => value<any>(rideControllerStart(id, { phoneLastFour })),
	arriveDestination: (id: number, confirmFarAway = false) => value<any>(rideControllerArriveDestination(id, { confirmFarAway })),
	finalize: (id: number, payload: any) => value<any>(rideControllerFinalize(id, payload)),
	reportLocation: (payload: any) => value<any>(rideControllerReportLocation(payload)),
	async payOrder(orderId: number) {
		const params: any = await orderControllerWechatJsapi(orderId) as any;
		await new Promise<void>((resolve, reject) => (uni as any).requestPayment({
			timeStamp: params.timeStamp, nonceStr: params.nonceStr, package: params.package,
			signType: params.signType || 'RSA', paySign: params.paySign, success: () => resolve(), fail: reject,
		}));
	},
};
