-- AlterTable
ALTER TABLE `Order` MODIFY `payMethod` ENUM('CASH', 'SHOUQIANBA', 'OFFLINE', 'WECHAT_JSAPI', 'WECHAT_MICROPAY', 'WASH_CARD', 'GROUP_BALANCE') NULL;

-- AlterTable
ALTER TABLE `RefundRecord` MODIFY `method` ENUM('CASH', 'SHOUQIANBA', 'OFFLINE', 'WECHAT_JSAPI', 'WECHAT_MICROPAY', 'WASH_CARD', 'GROUP_BALANCE') NULL;
