<template>
	<div v-loading="loading" class="page">
		<div class="head"><div><el-button link @click="$router.back()">← 返回</el-button><h2>行程订单 {{ trip?.order?.no || '' }}</h2></div><el-tag v-if="trip">{{ trip.status }}</el-tag></div>
		<RideAdminMap v-if="track" :origin="origin" :destination="destination" :planned-points="plannedPoints" :actual-points="actualPoints" height="520px" />
		<div class="grid" v-if="trip">
			<el-card header="行程信息"><el-descriptions :column="1" border><el-descriptions-item label="乘客">{{ trip.passenger?.name }}</el-descriptions-item><el-descriptions-item label="司机">{{ trip.driverEmployee?.name || '待接单' }}</el-descriptions-item><el-descriptions-item label="车辆">{{ trip.vehicle?.plateNumber || '-' }}</el-descriptions-item><el-descriptions-item label="起点">{{ trip.originAddress }}</el-descriptions-item><el-descriptions-item label="终点">{{ trip.destinationAddress }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ formatTime(trip.createdAt) }}</el-descriptions-item><el-descriptions-item label="派单截止">{{ formatTime(trip.dispatchExpireAt) }}</el-descriptions-item><el-descriptions-item label="到达上车点">{{ formatTime(trip.arrivedPickupAt) }}</el-descriptions-item><el-descriptions-item label="开始行程">{{ formatTime(trip.startedAt) }}</el-descriptions-item><el-descriptions-item label="到达目的地">{{ formatTime(trip.arrivedDestinationAt) }}</el-descriptions-item><el-descriptions-item label="完成/取消">{{ formatTime(trip.completedAt || trip.cancelledAt) }}</el-descriptions-item><el-descriptions-item v-if="trip.cancelReason" label="异常/取消原因">{{ trip.cancelReason }}</el-descriptions-item></el-descriptions></el-card>
			<el-card header="费用与结算"><el-descriptions :column="1" border><el-descriptions-item label="预付">¥{{ money(trip.order?.payAmount) }}</el-descriptions-item><el-descriptions-item label="最终">{{ trip.finalAmount == null ? '-' : `¥${money(trip.finalAmount)}` }}</el-descriptions-item><el-descriptions-item label="已退款">¥{{ money(trip.order?.refundedAmount) }}</el-descriptions-item><el-descriptions-item label="补款单">{{ trip.supplementOrder?.no || '-' }}</el-descriptions-item></el-descriptions><el-table :data="trip.extraFees||[]" size="small"><el-table-column prop="type" label="费用类型"/><el-table-column label="金额"><template #default="{row}">¥{{money(row.amount)}}</template></el-table-column><el-table-column prop="remark" label="备注"/></el-table></el-card>
		</div>
		<el-card v-if="trip" class="messages-card" header="行程聊天记录">
			<div v-if="messages.length" class="messages">
				<div v-for="message in messages" :key="message.id" class="message">
					<div class="message-meta"><strong>{{ senderName(message) }}</strong><span>{{ formatTime(message.createdAt) }}</span><el-tag size="small" :type="message.readAt ? 'success' : 'info'">{{ message.readAt ? '已读' : '未读' }}</el-tag></div>
					<div class="message-content">{{ message.content }}</div>
				</div>
			</div>
			<el-empty v-else description="本次行程暂无聊天消息" />
		</el-card>
	</div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { rideAdminControllerDetail, rideAdminControllerMessages, rideAdminControllerTrack } from '@wash/api-client'; import RideAdminMap from '../components/ride/RideAdminMap.vue';
const route=useRoute(); const loading=ref(false); const trip=ref<any>(null); const track=ref<any>(null); const messages=ref<any[]>([]);
const origin=computed(()=>track.value?{longitude:Number(track.value.originLongitude),latitude:Number(track.value.originLatitude),address:track.value.originAddress}:null); const destination=computed(()=>track.value?{longitude:Number(track.value.destinationLongitude),latitude:Number(track.value.destinationLatitude),address:track.value.destinationAddress}:null);
const plannedPoints=computed(()=>Array.isArray(track.value?.selectedRouteSnapshot?.points)?track.value.selectedRouteSnapshot.points:[]); const actualPoints=computed(()=>Array.isArray(track.value?.locations)?track.value.locations.map((p:any)=>({longitude:Number(p.longitude),latitude:Number(p.latitude)})):[]);
async function load(){loading.value=true;try{const id=Number(route.params.id);[trip.value,track.value,messages.value]=await Promise.all([rideAdminControllerDetail(id) as any,rideAdminControllerTrack(id) as any,rideAdminControllerMessages(id) as any]);}finally{loading.value=false}} function money(v:any){return Number(v||0).toFixed(2)} function formatTime(v?:string){return v?new Date(v).toLocaleString():'-'} function senderName(message:any){const senderId=Number(message?.senderMemberId);if(senderId===Number(trip.value?.passengerMemberId))return `乘客 · ${message?.senderMember?.name||trip.value?.passenger?.name||'未命名'}`;if(senderId===Number(trip.value?.driverMemberId))return `司机 · ${message?.senderMember?.name||trip.value?.driverEmployee?.name||'未命名'}`;return message?.senderMember?.name||`成员 #${senderId}`} onMounted(load);
</script>
<style scoped>.page{display:flex;flex-direction:column;gap:18px}.head{display:flex;justify-content:space-between;align-items:center}.head h2{display:inline;margin:0 0 0 12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.messages{display:flex;max-height:420px;flex-direction:column;gap:12px;overflow:auto;padding-right:6px}.message{padding:14px 16px;border:1px solid #e5e7eb;border-radius:12px;background:#f8fafc}.message-meta{display:flex;align-items:center;gap:10px;color:#64748b;font-size:13px}.message-meta strong{margin-right:auto;color:#1f2937}.message-content{margin-top:9px;color:#334155;line-height:1.65;white-space:pre-wrap;word-break:break-word}@media(max-width:960px){.grid{grid-template-columns:1fr}}</style>
