/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * OpenAPI spec version: 0.1.0
 */
import { createHttpClient } from '../../shared-utils/src/http';

/**
 * @summary Health check
 */
export type getHealthResponse = {
  data: void;
  status: number;
}

export const getGetHealthUrl = () => {


  return `/health`
}

export const getHealth = async ( options?: RequestInit): Promise<getHealthResponse> => {
return createHttpClient<Promise<getHealthResponse>>(getGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
  }
);}


