/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { AdjustMemberGrowthDtoRemark } from './adjustMemberGrowthDtoRemark';

export interface AdjustMemberGrowthDto {
  /** 变更值（可正可负，非0） */
  delta: number;
  /**
   * 备注（必填，前端会校验）
   * @nullable
   */
  remark?: AdjustMemberGrowthDtoRemark;
}
