/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export interface AssetCleanupDto {
  /** 资产ID列表（为空则不处理） */
  ids?: string[];
}
