/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { CartMyAddDtoSkuId } from './cartMyAddDtoSkuId';

export interface CartMyAddDto {
  /** 商品ID */
  productId: number;
  /** 数量（默认 1） */
  quantity?: number;
  /**
   * SKU ID（单规格可不传；多规格必传）
   * @nullable
   */
  skuId?: CartMyAddDtoSkuId;
}
