/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export interface CouponIssueDto {
  /** 发放张数，默认 1 */
  count?: number;
  /** 会员ID */
  memberId: number;
}
