/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 分组ID；不分组可传 null
 */
export type CouponUpdateDtoGroupId = { [key: string]: unknown };
