/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 发行总数（null 不限）
 */
export type CouponUpdateDtoIssueTotal = { [key: string]: unknown };
