/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { CouponUpdateDtoAdminRemark } from './couponUpdateDtoAdminRemark';
import type { CouponUpdateDtoApplyScope } from './couponUpdateDtoApplyScope';
import type { CouponUpdateDtoDescription } from './couponUpdateDtoDescription';
import type { CouponUpdateDtoEndAt } from './couponUpdateDtoEndAt';
import type { CouponUpdateDtoExpiryType } from './couponUpdateDtoExpiryType';
import type { CouponUpdateDtoFaceValue } from './couponUpdateDtoFaceValue';
import type { CouponUpdateDtoGroupId } from './couponUpdateDtoGroupId';
import type { CouponUpdateDtoImageUrl } from './couponUpdateDtoImageUrl';
import type { CouponUpdateDtoIssueTotal } from './couponUpdateDtoIssueTotal';
import type { CouponUpdateDtoMinOrderAmount } from './couponUpdateDtoMinOrderAmount';
import type { CouponUpdateDtoPerMemberLimit } from './couponUpdateDtoPerMemberLimit';
import type { CouponUpdateDtoRuleJson } from './couponUpdateDtoRuleJson';
import type { CouponUpdateDtoStartAt } from './couponUpdateDtoStartAt';
import type { CouponUpdateDtoType } from './couponUpdateDtoType';
import type { CouponUpdateDtoValidDays } from './couponUpdateDtoValidDays';

export interface CouponUpdateDto {
  adminRemark?: CouponUpdateDtoAdminRemark;
  allowCombine?: boolean;
  allowMiniappClaim?: boolean;
  allowStackWithMemberDiscount?: boolean;
  allowStackWithPoints?: boolean;
  /** 指定商品ID列表（applyScope=SPECIFIED 时使用） */
  applicableProductIds?: number[];
  applyScope?: CouponUpdateDtoApplyScope;
  description?: CouponUpdateDtoDescription;
  enabled?: boolean;
  /** 固定时间：结束时间（ISO 字符串） */
  endAt?: CouponUpdateDtoEndAt;
  expiryType?: CouponUpdateDtoExpiryType;
  /** 券面值（元） */
  faceValue?: CouponUpdateDtoFaceValue;
  /** 分组ID；不分组可传 null */
  groupId?: CouponUpdateDtoGroupId;
  imageUrl?: CouponUpdateDtoImageUrl;
  /** 发行总数（null 不限） */
  issueTotal?: CouponUpdateDtoIssueTotal;
  /** 最低订单额（元） */
  minOrderAmount?: CouponUpdateDtoMinOrderAmount;
  name: string;
  /** 每人限领（null 不限） */
  perMemberLimit?: CouponUpdateDtoPerMemberLimit;
  /** 规则 JSON（高级）。如 { kind: "direct", amount: 5 } */
  ruleJson?: CouponUpdateDtoRuleJson;
  /** 固定时间：开始时间（ISO 字符串） */
  startAt?: CouponUpdateDtoStartAt;
  /** 计次卡总次数 */
  totalTimes?: number;
  type: CouponUpdateDtoType;
  /** 领取后生效：有效天数 */
  validDays?: CouponUpdateDtoValidDays;
}
