/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 规则 JSON（高级）。如 { kind: "direct", amount: 5 }
 */
export type CouponCreateDtoRuleJson = { [key: string]: unknown };
