/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export type CouponCreateDtoType = typeof CouponCreateDtoType[keyof typeof CouponCreateDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CouponCreateDtoType = {
  COUPON: 'COUPON',
  WASH_CARD: 'WASH_CARD',
  GROUP_WASH_CARD: 'GROUP_WASH_CARD',
} as const;
