/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export interface CouponGroupCreateDto {
  /** 备注/描述 */
  description?: string;
  /** 是否启用 */
  enabled?: boolean;
  /** 分组名称 */
  name: string;
  /** 排序权重（越大越靠前） */
  weight?: number;
}
