/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMemberDtoAvatarUrl } from './createMemberDtoAvatarUrl';

export interface CreateMemberDto {
  /**
   * 头像URL（可选）
   * @nullable
   */
  avatarUrl?: CreateMemberDtoAvatarUrl;
  /** 余额（可选） */
  balance?: number;
  /** 会员分类ID */
  categoryId: number;
  /** 会员等级ID */
  levelId: number;
  /** 昵称（≤10字符） */
  name: string;
  /** 初始密码（可选） */
  password?: string;
  /** 手机号 */
  phone: string;
  /** 积分（可选） */
  points?: number;
  /** 标签ID列表（可选） */
  tagIds?: number[];
}
