/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAdminDtoAvatarUrl } from './createAdminDtoAvatarUrl';

export interface CreateAdminDto {
  /**
   * 头像URL（可为空）
   * @nullable
   */
  avatarUrl?: CreateAdminDtoAvatarUrl;
  /** 昵称 */
  name?: string;
  /** 密码（>=6位） */
  password: string;
  /** 手机号 */
  phone: string;
  /** 角色ID */
  roleId: number;
}
