/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * OpenAPI spec version: 0.1.0
 */

export type GetContentNoticesActiveType = typeof GetContentNoticesActiveType[keyof typeof GetContentNoticesActiveType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetContentNoticesActiveType = {
  home: 'home',
  store: 'store',
} as const;
