/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * OpenAPI spec version: 0.1.0
 */
import type { GetContentNoticesType } from './getContentNoticesType';

export type GetContentNoticesParams = {
type?: GetContentNoticesType;
};
