/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * OpenAPI spec version: 0.1.0
 */
import type { GetContentNoticesActiveType } from './getContentNoticesActiveType';

export type GetContentNoticesActiveParams = {
type: GetContentNoticesActiveType;
};
