/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 有效期（ISO 字符串；null/不传 表示永久）
 */
export type GroupCardCreateDtoExpiryAt = { [key: string]: unknown };
