/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { GroupCardConsumeDtoMemberId } from './groupCardConsumeDtoMemberId';
import type { GroupCardConsumeDtoPurchaseOrderId } from './groupCardConsumeDtoPurchaseOrderId';
import type { GroupCardConsumeDtoReason } from './groupCardConsumeDtoReason';
import type { GroupCardConsumeDtoRefundRecordId } from './groupCardConsumeDtoRefundRecordId';
import type { GroupCardConsumeDtoRemark } from './groupCardConsumeDtoRemark';
import type { GroupCardConsumeDtoServiceOrderId } from './groupCardConsumeDtoServiceOrderId';
import type { GroupCardConsumeDtoVehicleId } from './groupCardConsumeDtoVehicleId';

export interface GroupCardConsumeDto {
  /** 会员ID（可为 null） */
  memberId?: GroupCardConsumeDtoMemberId;
  /** 购卡订单ID（可为 null） */
  purchaseOrderId?: GroupCardConsumeDtoPurchaseOrderId;
  reason?: GroupCardConsumeDtoReason;
  /** 退款记录ID（可为 null） */
  refundRecordId?: GroupCardConsumeDtoRefundRecordId;
  /** 备注（可为 null） */
  remark?: GroupCardConsumeDtoRemark;
  /** 服务订单ID（可为 null） */
  serviceOrderId?: GroupCardConsumeDtoServiceOrderId;
  /** 扣减次数 */
  times: number;
  /** 服务车辆ID（可为 null） */
  vehicleId?: GroupCardConsumeDtoVehicleId;
}
