/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { GroupUpdateDtoIconUrl } from './groupUpdateDtoIconUrl';
import type { GroupUpdateDtoRemark } from './groupUpdateDtoRemark';

export interface GroupUpdateDto {
  /** 集团图标 URL（传 null 表示清空） */
  iconUrl?: GroupUpdateDtoIconUrl;
  /** 集团名称 */
  name?: string;
  /** 备注（可为 null） */
  remark?: GroupUpdateDtoRemark;
}
