/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { GroupVehicleCreateDtoBrand } from './groupVehicleCreateDtoBrand';
import type { GroupVehicleCreateDtoBrandId } from './groupVehicleCreateDtoBrandId';
import type { GroupVehicleCreateDtoColor } from './groupVehicleCreateDtoColor';
import type { GroupVehicleCreateDtoSeries } from './groupVehicleCreateDtoSeries';
import type { GroupVehicleCreateDtoSeriesId } from './groupVehicleCreateDtoSeriesId';
import type { GroupVehicleCreateDtoTypeSub } from './groupVehicleCreateDtoTypeSub';
import type { GroupVehicleCreateDtoVin } from './groupVehicleCreateDtoVin';

export interface GroupVehicleCreateDto {
  brand?: GroupVehicleCreateDtoBrand;
  brandId?: GroupVehicleCreateDtoBrandId;
  color?: GroupVehicleCreateDtoColor;
  /** 车牌号 */
  plateNumber: string;
  series?: GroupVehicleCreateDtoSeries;
  seriesId?: GroupVehicleCreateDtoSeriesId;
  /** 车辆主类型 */
  typeMain: string;
  typeSub?: GroupVehicleCreateDtoTypeSub;
  vin?: GroupVehicleCreateDtoVin;
}
