/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { GroupBalanceRechargeDtoRemark } from './groupBalanceRechargeDtoRemark';

export interface GroupBalanceRechargeDto {
  /** 充值金额（元） */
  amount: number;
  /** 付款会员ID（集团管理员） */
  memberIdForPayment: number;
  /** 备注（可为 null） */
  remark?: GroupBalanceRechargeDtoRemark;
}
