/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * OpenAPI spec version: 0.1.0
 */

export * from './getContentNoticesActiveParams';
export * from './getContentNoticesActiveType';
export * from './getContentNoticesParams';
export * from './getContentNoticesType';
export * from './postContentNoticesBody';
export * from './putContentNoticesIdBody';