/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export interface LoginDto {
  /** 密码（至少6位） */
  password: string;
  /** 手机号 */
  phone: string;
}
