/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationControllerListStatus } from './notificationControllerListStatus';

export type NotificationControllerListParams = {
/**
 * 状态筛选
 */
status?: NotificationControllerListStatus;
/**
 * 拉取条数，1~200
 */
take?: number;
/**
 * 跳过条数
 */
skip?: number;
};
