/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export type NotificationControllerListStatus = typeof NotificationControllerListStatus[keyof typeof NotificationControllerListStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationControllerListStatus = {
  UNREAD: 'UNREAD',
  READ: 'READ',
} as const;
