/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export type OrderControllerListReviewsParams = {
page: string;
pageSize: string;
memberId: string;
orderNo: string;
ratingMin: string;
ratingMax: string;
start: string;
end: string;
};
