/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 单规格库存（specType=SINGLE 且 type!=SERVICE 时）
 * @nullable
 */
export type StoreProductCreateDtoStockQuantity = { [key: string]: unknown } | null;
