/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 绑定卡券ID（传 null 断开）
 * @nullable
 */
export type StoreProductUpdateDtoCouponId = { [key: string]: unknown } | null;
