/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { StoreProductSkuUpsertDtoBarcode } from './storeProductSkuUpsertDtoBarcode';
import type { StoreProductSkuUpsertDtoCouponId } from './storeProductSkuUpsertDtoCouponId';
import type { StoreProductSkuUpsertDtoImageUrl } from './storeProductSkuUpsertDtoImageUrl';
import type { StoreProductSpecPairDto } from './storeProductSpecPairDto';

export interface StoreProductSkuUpsertDto {
  /**
   * 条码（可为空）
   * @nullable
   */
  barcode?: StoreProductSkuUpsertDtoBarcode;
  /**
   * 绑定卡券ID（虚拟卡券商品用，可为空）
   * @nullable
   */
  couponId?: StoreProductSkuUpsertDtoCouponId;
  /** 是否启用 */
  enabled?: boolean;
  /** SKU ID（更新时传；创建时不传） */
  id?: number;
  /**
   * SKU 图片 URL/相对路径（可为空）
   * @nullable
   */
  imageUrl?: StoreProductSkuUpsertDtoImageUrl;
  /** 划线价 */
  listPrice?: number;
  /** SKU 名称（可不传，服务端会根据 specsJson 生成默认名） */
  name?: string;
  /** 价格 */
  price?: number;
  /** SKU 编码（可不传，服务端会生成） */
  skuCode?: string;
  /** SKU 规格值列表 */
  specsJson?: StoreProductSpecPairDto[];
  /** 库存（服务商品会被服务端归零） */
  stockQuantity?: number;
}
