/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { StoreProductCreateDtoBarcode } from './storeProductCreateDtoBarcode';
import type { StoreProductCreateDtoCategoryId } from './storeProductCreateDtoCategoryId';
import type { StoreProductCreateDtoCouponId } from './storeProductCreateDtoCouponId';
import type { StoreProductCreateDtoDescription } from './storeProductCreateDtoDescription';
import type { StoreProductCreateDtoImageUrl } from './storeProductCreateDtoImageUrl';
import type { StoreProductCreateDtoListPrice } from './storeProductCreateDtoListPrice';
import type { StoreProductCreateDtoPrice } from './storeProductCreateDtoPrice';
import type { StoreProductSkuUpsertDto } from './storeProductSkuUpsertDto';
import type { StoreProductSpecsDefinitionItemDto } from './storeProductSpecsDefinitionItemDto';
import type { StoreProductCreateDtoSpecType } from './storeProductCreateDtoSpecType';
import type { StoreProductCreateDtoStockQuantity } from './storeProductCreateDtoStockQuantity';
import type { StoreProductCreateDtoType } from './storeProductCreateDtoType';

export interface StoreProductCreateDto {
  /**
   * 条码（可为空）
   * @nullable
   */
  barcode?: StoreProductCreateDtoBarcode;
  /**
   * 分类ID（可为空）
   * @nullable
   */
  categoryId?: StoreProductCreateDtoCategoryId;
  /**
   * 绑定卡券ID（虚拟卡券商品用）
   * @nullable
   */
  couponId?: StoreProductCreateDtoCouponId;
  /**
   * 商品介绍 HTML
   * @nullable
   */
  description?: StoreProductCreateDtoDescription;
  /** 是否上架 */
  enabled?: boolean;
  /** 商品图片列表（首张建议与 imageUrl 一致） */
  imagesJson?: string[];
  /**
   * 主图 URL/相对路径
   * @nullable
   */
  imageUrl?: StoreProductCreateDtoImageUrl;
  /** 初始销量（用于展示叠加） */
  initialSales?: number;
  /** 是否计为洗车（次）（服务商品用） */
  isCarWash?: boolean;
  /**
   * 单规格划线价（specType=SINGLE 时）
   * @nullable
   */
  listPrice?: StoreProductCreateDtoListPrice;
  /** 是否参与会员折扣 */
  memberDiscount?: boolean;
  /** 商品名称 */
  name: string;
  /** 是否允许积分抵扣 */
  pointsDeductible?: boolean;
  /**
   * 单规格价格（specType=SINGLE 时）
   * @nullable
   */
  price?: StoreProductCreateDtoPrice;
  /** 卖点 */
  sellPoint?: string;
  /** 允许快递（实物商品用） */
  shipAllowExpress?: boolean;
  /** 允许到店自提（实物商品用） */
  shipAllowPickup?: boolean;
  /** 多规格：SKU 列表 */
  skus?: StoreProductSkuUpsertDto[];
  /** 排序权重（越大越靠前） */
  sortWeight?: number;
  /**
   * 多规格：规格项定义
   * @nullable
   */
  specsDefinitionJson?: StoreProductSpecsDefinitionItemDto[] | null;
  /** 规格类型 */
  specType: StoreProductCreateDtoSpecType;
  /**
   * 单规格库存（specType=SINGLE 且 type!=SERVICE 时）
   * @nullable
   */
  stockQuantity?: StoreProductCreateDtoStockQuantity;
  /** 商品类型 */
  type: StoreProductCreateDtoType;
}
