/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 商品类型
 */
export type StoreProductCreateDtoType = typeof StoreProductCreateDtoType[keyof typeof StoreProductCreateDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StoreProductCreateDtoType = {
  SERVICE: 'SERVICE',
  PHYSICAL: 'PHYSICAL',
  VIRTUAL_CARD: 'VIRTUAL_CARD',
} as const;
