/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

export interface SystemBusinessHoursDto {
  /** 营业结束时间（HH:mm） */
  end?: string;
  /** 营业开始时间（HH:mm） */
  start?: string;
}
