/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */

/**
 * 开始时间（ISO字符串）
 * @nullable
 */
export type UpdateMemberCouponExpiryDtoStartAt = { [key: string]: unknown } | null;
