/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Wash Club API
 * API for 一体化洗车门店管理平台
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleMyCreateDtoBrand } from './vehicleMyCreateDtoBrand';
import type { VehicleMyCreateDtoBrandId } from './vehicleMyCreateDtoBrandId';
import type { VehicleMyCreateDtoColor } from './vehicleMyCreateDtoColor';
import type { VehicleMyCreateDtoSeries } from './vehicleMyCreateDtoSeries';
import type { VehicleMyCreateDtoSeriesId } from './vehicleMyCreateDtoSeriesId';
import type { VehicleMyCreateDtoTypeSub } from './vehicleMyCreateDtoTypeSub';
import type { VehicleMyCreateDtoVin } from './vehicleMyCreateDtoVin';

export interface VehicleMyCreateDto {
  /**
   * 品牌（中文名，可选）
   * @nullable
   */
  brand?: VehicleMyCreateDtoBrand;
  /**
   * 车型品牌ID（第三方库，可选）
   * @nullable
   */
  brandId?: VehicleMyCreateDtoBrandId;
  /**
   * 车辆颜色（可选）
   * @nullable
   */
  color?: VehicleMyCreateDtoColor;
  /** 是否设为默认车辆 */
  isDefault?: boolean;
  /** 车牌号 */
  plateNumber: string;
  /**
   * 车系（中文名，可选）
   * @nullable
   */
  series?: VehicleMyCreateDtoSeries;
  /**
   * 车型车系ID（第三方库，可选）
   * @nullable
   */
  seriesId?: VehicleMyCreateDtoSeriesId;
  /** 车辆主类 */
  typeMain: string;
  /**
   * 车辆子类（可选）
   * @nullable
   */
  typeSub?: VehicleMyCreateDtoTypeSub;
  /**
   * VIN（可选）
   * @nullable
   */
  vin?: VehicleMyCreateDtoVin;
}
