<template><view class="page"><RideMap :markers="markers" :route-points="routePoints"/><RideStatusBar title="内部司机" :subtitle="statusText"><view class="orders-link" @tap="goOrders">行程订单</view></RideStatusBar>
	<view class="status-panel" :style="statusPanelStyle"><view class="switches"><button size="mini" :class="{active:status==='AVAILABLE'}" @tap="setStatus('AVAILABLE')">空闲</button><button size="mini" :class="{active:status==='BUSY'}" @tap="setStatus('BUSY')">忙碌</button><button size="mini" :class="{active:status==='OFFLINE'}" @tap="setStatus('OFFLINE')">离线</button></view><view class="vehicle" @tap="manageVehicles">出车车辆：{{currentVehicle?.vehicle?.plateNumber||'点击选择/新增'}}</view></view>
	<view class="order-card" v-if="activeTrip"><view class="order-head"><strong>{{tripTitle}}</strong><text>#{{activeTrip.id}}</text></view><view>乘客：{{activeTrip.passenger?.name||'-'}}</view><view>起点：{{activeTrip.originAddress}}</view><view>终点：{{activeTrip.destinationAddress}}</view><RideSlideAction v-if="activeTrip.status==='TO_PICKUP'" label="滑动确认到达上车点" @confirm="arrivePickup"/><RideSlideAction v-else-if="activeTrip.status==='ARRIVED_PICKUP'" label="滑动验证并开始订单" @confirm="startTrip"/><RideSlideAction v-else-if="activeTrip.status==='IN_TRIP'" label="滑动确认到达目的地" @confirm="arriveDestination"/><button v-else-if="activeTrip.status==='ARRIVED_DESTINATION'" class="primary" @tap="goFare">确认费用</button></view>
	<view class="dispatch" v-else-if="dispatching.length"><strong>新行程订单</strong><view v-for="trip in dispatching" :key="trip.id" class="dispatch-row"><view><text>{{trip.originAddress}}</text><text>→ {{trip.destinationAddress}}</text></view><button size="mini" @tap="accept(trip.id)">接单</button><button size="mini" @tap="reject(trip.id)">拒绝</button></view></view>
	<view v-else class="empty">{{status==='AVAILABLE'?'正在等待新订单':'切换为空闲后可接收派单'}}</view></view></template>
<script setup lang="ts">
import{computed,onBeforeUnmount,onMounted,ref}from'vue';import RideMap from '../../../components/ride/RideMap.vue';import RideStatusBar from '../../../components/ride/RideStatusBar.vue';import RideSlideAction from '../../../components/ride/RideSlideAction.vue';import{rideApi}from'../../../services/ride';import{onRideRealtime,startDriverLocationTracking}from'../../../services/ride-realtime';import{getCurrentRideLocation,locationErrorMessage}from'../../../services/geolocation';import{useSafeArea}from'../../../utils/safe-area';
const profile=ref<any>(null),vehicles=ref<any[]>([]),orders=ref<any[]>([]),routePoints=ref<any[]>([]);let stopTracking:(()=>void)|null=null,stopRealtime:(()=>void)|null=null,poll:any;
const safeArea=useSafeArea();const statusPanelStyle=computed(()=>({top:`${safeArea.topSpacerHeight+88}px`}));
const status=computed(()=>profile.value?.availabilityStatus||'OFFLINE');const statusText=computed(()=>({AVAILABLE:'空闲接单中',BUSY:'忙碌，不参与派单',OFFLINE:'当前离线'}as any)[status.value]);const currentVehicle=computed(()=>vehicles.value.find(v=>v.id===profile.value?.currentVehicleId));const activeTrip=computed(()=>orders.value.find(t=>['TO_PICKUP','ARRIVED_PICKUP','IN_TRIP','ARRIVED_DESTINATION','FARE_PENDING','SUPPLEMENT_PENDING'].includes(t.status)));const dispatching=computed(()=>orders.value.filter(t=>t.status==='DISPATCHING'));const tripTitle=computed(()=>({TO_PICKUP:'前往乘客上车点',ARRIVED_PICKUP:'等待乘客验证',IN_TRIP:'行程进行中',ARRIVED_DESTINATION:'已到目的地'}as any)[activeTrip.value?.status]||activeTrip.value?.status);
const markers=computed(()=>{const t=activeTrip.value;if(!t)return[];const list:any[]=[{id:1,longitude:Number(t.originLongitude),latitude:Number(t.originLatitude),title:'乘客上车点'} ,{id:2,longitude:Number(t.destinationLongitude),latitude:Number(t.destinationLatitude),title:'目的地'}];const loc=t.locations?.[0];if(loc)list.push({id:3,longitude:Number(loc.longitude),latitude:Number(loc.latitude),title:'我的位置',kind:'driver-current'});return list});
async function load(){profile.value=await rideApi.driverProfile();vehicles.value=await rideApi.driverVehicles();const d=await rideApi.driverOrders({page:1,pageSize:30});orders.value=d?.items||[]}
async function setStatus(next:any){try{if(next!=='OFFLINE'){const location=await getCurrentRideLocation();try{await rideApi.reportLocation({longitude:location.longitude,latitude:location.latitude,heading:Number.isFinite(location.heading)?location.heading:undefined,speedMetersPerSecond:Number.isFinite(location.speed)?Math.max(0,Number(location.speed)):undefined,clientTimestamp:new Date().toISOString()})}catch(error:any){if(!/过于频繁/.test(String(error?.message||'')))throw error}}profile.value=await rideApi.driverStatus(next);if(next!=='OFFLINE'&&!stopTracking)stopTracking=startDriverLocationTracking(r=>{if(r?.route)routePoints.value=r.route.points||[]});if(next==='OFFLINE'&&stopTracking){stopTracking();stopTracking=null}}catch(e:any){uni.showToast({title:locationErrorMessage(e)||e?.message||'状态切换失败',icon:'none'})}}
async function accept(id:number){try{await rideApi.accept(id);await load()}catch(e:any){uni.showToast({title:e?.message||'订单已被接走',icon:'none'})}}async function reject(id:number){await rideApi.reject(id);await load()}async function arrivePickup(){await rideApi.arrivePickup(activeTrip.value.id);await load()}
async function startTrip(){uni.showModal({title:'验证乘客',editable:true,placeholderText:'请输入手机号后四位',success:async r=>{if(r.confirm&&r.content){try{await rideApi.start(activeTrip.value.id,r.content);await load()}catch(e:any){uni.showToast({title:e?.message||'验证失败',icon:'none'})}}}})}async function arriveDestination(){await rideApi.arriveDestination(activeTrip.value.id);await load()}function goFare(){uni.navigateTo({url:`/pages/ride/fare-confirm/index?id=${activeTrip.value.id}`})}function goOrders(){uni.navigateTo({url:'/pages/ride/orders/index?driver=1'})}
async function manageVehicles(){if(!vehicles.value.length){uni.showModal({title:'新增出车车辆',editable:true,placeholderText:'输入车牌号',success:async r=>{if(r.confirm&&r.content){await rideApi.createDriverVehicle({plateNumber:r.content,typeMain:'轿车'});await load();manageVehicles()}}});return}const names=vehicles.value.map(v=>v.vehicle.plateNumber);uni.showActionSheet({itemList:[...names,'新增车辆'],success:async r=>{if(r.tapIndex===names.length){vehicles.value=[];manageVehicles();return}await rideApi.updateDriverVehicle(vehicles.value[r.tapIndex].id,{selected:true,enabled:true});await load()}})}
onMounted(async()=>{await load();if(status.value!=='OFFLINE')stopTracking=startDriverLocationTracking(r=>{if(r?.route)routePoints.value=r.route.points||[]});stopRealtime=onRideRealtime(()=>load());poll=setInterval(load,8000)});onBeforeUnmount(()=>{stopTracking?.();stopRealtime?.();clearInterval(poll)});
</script>
<style scoped>.page{height:100vh;position:relative;overflow:hidden}.status-panel,.order-card,.dispatch,.empty{position:absolute;z-index:20;left:20rpx;right:20rpx;bottom:calc(24rpx + env(safe-area-inset-bottom));background:#fff;border-radius:28rpx;padding:22rpx;box-shadow:0 12rpx 40rpx rgba(15,23,42,.18)}.status-panel{bottom:auto}.switches{display:flex;gap:10rpx}.switches button{flex:1}.switches .active{background:#0f172a;color:#fff}.vehicle{margin-top:12rpx;color:#475569}.order-card{display:flex;flex-direction:column;gap:12rpx}.order-head{display:flex;justify-content:space-between}.dispatch-row{display:flex;align-items:center;gap:10rpx;padding:12rpx 0;border-top:1px solid #e2e8f0}.dispatch-row view{flex:1}.dispatch-row text{display:block}.primary{background:#0f172a;color:#fff}.orders-link{margin-left:auto;color:#2563eb;font-size:24rpx}.empty{text-align:center;color:#64748b}</style>
